name: lint

on:
  push:
    branches: '*'
  pull_request:
    branches: '*'

jobs:
  build:
    runs-on: ubuntu-latest
    name: Format & Lint & Type Check
    steps:
      - name: Setup repo
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install -qq --upgrade pip
          pip install -qq poetry
          poetry install
      - name: Check format checking
        run: |
          poetry run task check-format
      - name: Perform lint checking
        run: |
          poetry run task lint --disable=E --exit-zero
          poetry run task lint -E
      - name: Perform type checking
        run: |
          poetry run task types
